version: '3.8'

services:
  app:
    build: .
    container_name: playcorner-app
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - playcorner_net

  db:
    image: postgres:15-alpine
    container_name: playcorner-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Jakarta
    ports:
      - "5101:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - playcorner_net

  nginx:
    image: nginx:1.25-alpine
    container_name: playcorner-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/dist:/usr/share/nginx/html
      - ./nginx/www:/var/www/certbot
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - ./nginx/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem
    depends_on:
      - app
    networks:
      - playcorner_net

networks:
  playcorner_net:
    driver: bridge

volumes:
  postgres-data:
